In [79]:
import torch

In [80]:
# ex 2
random_tens = torch.rand(size=(7,7))
print(random_tens)

tensor([[0.8549, 0.5509, 0.2868, 0.2063, 0.4451, 0.3593, 0.7204],
        [0.0731, 0.9699, 0.1078, 0.8829, 0.4132, 0.7572, 0.6948],
        [0.5209, 0.5932, 0.8797, 0.6286, 0.7653, 0.1132, 0.8559],
        [0.6721, 0.6267, 0.5691, 0.7437, 0.9592, 0.3887, 0.2214],
        [0.3742, 0.1953, 0.7405, 0.2529, 0.2332, 0.9314, 0.9575],
        [0.5575, 0.4134, 0.4355, 0.7369, 0.0331, 0.0914, 0.8994],
        [0.9936, 0.4703, 0.1049, 0.5137, 0.2674, 0.4990, 0.7447]])


In [81]:
# ex 3
second_tens = torch.rand(size=(1,7))
product = random_tens.matmul(second_tens.T)
print(product)

tensor([[1.6914],
        [1.7581],
        [2.0906],
        [1.8975],
        [1.7585],
        [1.7961],
        [1.8900]])


In [82]:
# ex 4
torch.manual_seed(0)
first_tens = torch.rand(7,7)
second_tens = torch.rand(1,7)
product = first_tens.matmul(second_tens.T)

print(first_tens,second_tens,product)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]) tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]) tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])


In [83]:
# ex 5
torch.cuda.manual_seed(1234)

In [84]:
# ex 6
device = 'cuda'
torch.manual_seed(1234)
first_on_gpu = torch.rand(size=(2,3)).to(device)
second_on_gpu = torch.rand(size=(2,3)).to(device)


In [85]:
# ex 7
product_on_gpu = first_on_gpu.matmul(second_on_gpu.T)
print(product_on_gpu)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')


In [86]:
# ex 8
min_val = torch.min(product_on_gpu)
max_val = torch.max(product_on_gpu)
print(min_val,max_val)

tensor(0.3647, device='cuda:0') tensor(0.5617, device='cuda:0')


In [87]:
# ex 9
min_index = torch.argmin(product_on_gpu)
max_index = torch.argmax(product_on_gpu)
print(min_index,max_index)

tensor(0, device='cuda:0') tensor(3, device='cuda:0')


In [ ]:
import torch.share

# ex 10
torch.manual_seed(7)
tensor = torch.rand(size=(1,1,1,10))
flat_tensor = torch.squeeze(tensor)
print(tensor,tensor.size())
print(flat_tensor,flat_tensor.size())

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
